1. Load the Academic Performance dataset in data frame object.
2. Check null values in the dataset.
3. Count the number of null values in complete data set (Hint: eplace the null values with standard null value NaN)
4. Dropping rows with at least 1 null value
5. Dropping rows if all values in that row are missing
6. Dropping columns with at least 1 null value.
7. Dropping Rows with at least 1 null value in CSV file

In [4]:
import pandas as pd     
import numpy as np

In [5]:
df=pd.read_csv("StudentsPerformanceTest1.csv")
df.head(5)

,gender,math score,reading score,writing score,Placement Score,placement offer count,Region
0,female,72,72,74.0,78.0,1,Pune
1,female,69,90,88.0,NaN,2,na
2,female,90,95,93.0,74.0,2,Nashik
3,male,47,57,NaN,78.0,1,Na
4,male,na,78,75.0,81.0,3,Pune

In [6]:
df=df.replace(["na","NaN","null","Na"],np.nan,inplace=True)
df.isnull().sum()

gender                   0
math score               2
reading score            1
writing score            1
Placement Score          1
placement offer count    0
Region                   4
dtype: int64

In [7]:
print("\nNull values in each column:\n", df.isnull().sum())
print("\nTotal null values:", df.isnull().sum().sum())

Null values in each column:
 gender                   0
math score               2
reading score            1
writing score            1
Placement Score          1
placement offer count    0
Region                   4
dtype: int64

Total null values: 9

In [8]:
df_drop_row = df.dropna()
df_drop_row

,gender,math score,reading score,writing score,Placement Score,placement offer count,Region
0,female,72,72,74.0,78.0,1,Pune
2,female,90,95,93.0,74.0,2,Nashik
6,male,12,44,52.0,12.0,2,Nashik

In [9]:
df_drop_col = df.dropna(axis=1)
df_drop_col

   gender  placement offer count
0  female                      1
1  female                      2
2  female                      2
3    male                      1
4    male                      3
5  female                      4
6    male                      2
7    male                      1
8    male                      0