In [1]:
import pandas as pd   
import numpy as np          
import seaborn as sns      
import matplotlib.pyplot as plt

In [2]:
url="https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

In [6]:
df=pd.read_csv(url,header=None,names=["sep_len","sep_wid","pet_len","pet_wid","spe"])
df.head(5)

   sep_len  sep_wid  pet_len  pet_wid          spe
0      5.1      3.5      1.4      0.2  Iris-setosa
1      4.9      3.0      1.4      0.2  Iris-setosa
2      4.7      3.2      1.3      0.2  Iris-setosa
3      4.6      3.1      1.5      0.2  Iris-setosa
4      5.0      3.6      1.4      0.2  Iris-setosa

In [10]:
encode_df=pd.get_dummies(df,columns=["spe"])

In [11]:
encode_df.head(10)

,sep_len,sep_wid,pet_len,pet_wid,spe_Iris-setosa,spe_Iris-versicolor,spe_Iris-virginica
0,5.1,3.5,1.4,0.2,True,False,False
1,4.9,3.0,1.4,0.2,True,False,False
2,4.7,3.2,1.3,0.2,True,False,False
3,4.6,3.1,1.5,0.2,True,False,False
4,5.0,3.6,1.4,0.2,True,False,False
5,5.4,3.9,1.7,0.4,True,False,False
6,4.6,3.4,1.4,0.3,True,False,False
7,5.0,3.4,1.5,0.2,True,False,False
8,4.4,2.9,1.4,0.2,True,False,False
9,4.9,3.1,1.5,0.1,True,False,False

array([0, 1, 2])