# 1. Creation of Dataset " StudentsPerformance" using Microsoft Excel.
The features of dataset are: Math_Score, Reading_Score, Writing_Score, Placement_Score, Club_Join_Date
Range of Values: Math_Score [60-80], Reading_Score[75-,95], ,Writing_Score [60,80], Placement_Score[75-100], Club_Join_Date [2018-2021].
Response VAriable : Placement Score
In 20% data, fill the impurities.

In [1]:
import pandas as pd     
import numpy as np

In [2]:
np.random.seed(0)
n=100

In [3]:
data_dic={
    "Math_Score": np.random.randint(60,80,n) ,
    "Reading_Score": np.random.randint(60,80,n) ,
    "Writing_Score":  np.random.randint(60,80,n) ,
    "Placement_Score": np.random.randint(60,80,n) ,
    "Club_Join_Date": np.random.choice(pd.date_range("2018-1-1","2021-12-30"),n)
}

In [4]:
df=pd.DataFrame(data_dic)
df.head(5)

   Math_Score  Reading_Score  Writing_Score  Placement_Score Club_Join_Date
0          72             73             79               65     2020-04-17
1          75             76             74               60     2018-05-15
2          60             67             63               68     2018-01-04
3          63             69             63               75     2021-06-04
4          63             60             67               75     2020-06-08

In [5]:
for col in df.columns:
     df.loc[np.random.choice(df.index, int(0.2*n), replace=False), col] = np.nan

In [6]:
df.head(50)

    Math_Score  Reading_Score  Writing_Score  Placement_Score Club_Join_Date
0          NaN           73.0           79.0             65.0     2020-04-17
1         75.0           76.0            NaN             60.0     2018-05-15
2          NaN           67.0           63.0             68.0     2018-01-04
3         63.0           69.0           63.0             75.0     2021-06-04
4         63.0           60.0           67.0             75.0            NaT
5         67.0           70.0           69.0             71.0     2019-11-12
6         69.0           78.0           69.0             64.0     2019-03-21
7         79.0           71.0           69.0             67.0     2021-12-12
8         78.0           62.0            NaN             73.0     2021-08-01
9          NaN           62.0           74.0             70.0     2020-04-16
10        66.0           63.0           78.0             74.0            NaT
11         NaN            NaN           72.0             77.0     2020-01-07
12        61.0           78.0           63.0              NaN     2018-09-06
13         NaN           74.0           69.0             63.0     2019-01-01
14        67.0            NaN           70.0              NaN     2021-05-10
15         NaN           77.0           73.0             78.0     2018-07-17
16        77.0            NaN           67.0             62.0     2020-07-18
17        65.0            NaN           67.0             79.0     2019-09-30
18        73.0           69.0           61.0             71.0     2019-08-30
19         NaN           61.0           72.0             78.0            NaT
20        69.0           64.0           62.0             73.0            NaT
21        79.0            NaN           62.0             61.0     2020-05-02
22        76.0           71.0           61.0             66.0            NaT
23        79.0            NaN           65.0             70.0     2018-08-02
24        65.0           71.0            NaN             76.0     2021-09-09
25        75.0           62.0            NaN              NaN     2018-04-13
26        75.0           79.0           60.0             63.0     2018-11-24
27        60.0           76.0           71.0              NaN     2019-08-19
28        78.0           60.0           62.0              NaN     2021-06-01
29         NaN           60.0           65.0             69.0     2018-09-14
30        77.0           66.0           76.0             72.0            NaT
31        79.0            NaN            NaN             73.0     2021-02-05
32        79.0           74.0           61.0             66.0            NaT
33        79.0           70.0           77.0             66.0            NaT
34        74.0            NaN           76.0              NaN     2021-11-17
35        67.0           68.0           63.0             68.0     2018-01-01
36        60.0           73.0           68.0             73.0     2021-10-16
37        61.0           62.0           64.0             67.0     2019-11-23
38        69.0           63.0           76.0             76.0     2021-01-18
39         NaN           62.0           63.0             75.0     2021-01-03
40         NaN            NaN           67.0             68.0     2019-05-15
41         NaN           73.0           63.0             63.0     2020-01-09
42        71.0           76.0           78.0             66.0     2019-09-28
43        78.0           68.0           77.0             77.0            NaT
44        62.0            NaN           61.0             67.0            NaT
45        60.0            NaN           78.0             62.0     2020-05-01
46        60.0            NaN            NaN              NaN     2018-10-10
47        64.0           62.0           62.0             78.0     2019-12-20
48        65.0           63.0           65.0             73.0            NaT
49         NaN           72.0            NaN              NaN     2021-02-13

In [8]:
df.isnull().sum()

Math_Score         20
Reading_Score      20
Writing_Score      20
Placement_Score    20
Club_Join_Date     20
dtype: int64